# Generated by Django 4.1 on 2022-08-26 11:49

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(max_length=255, verbose_name='Содержание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, verbose_name='Слаг')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги')),
            ],
        ),
    ]
